[package]
name = "day19_part1"
version = "0.1.0"
authors = ["Fred Lahde <frederick.lahde@worldiety.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

